/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dynsys.Chirikov;
import dynsys.DiffEq;
import dynsys.DiffEq2D;
import dynsys.DuffingEq;
import dynsys.DynSys;
import dynsys.DynSys.Area;
import dynsys.FractalRandIFS;
import dynsys.IFS;
import dynsys.IFS.CommonIFS;
import dynsys.MapDS;
import dynsys.MapDS2D;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author 122
 */
public class MyJFrame extends javax.swing.JFrame {

    DynSys ds;

    String[] maps = {"Chirikov"};
    String[] des = {"DuffingEq"};
    String[] fractals = {"IFS (rand)"};

    /**
     * Creates new form MyJFrame
     */
    public MyJFrame() {
        initComponents();
        ds = ((DrawPanel) drawPanel).getDs();

        drawPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameSys = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        sampleList = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        frameRK4 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFiters = new javax.swing.JTextField();
        jTFstep = new javax.swing.JTextField();
        buSetRK4 = new javax.swing.JButton();
        frameChirikov = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jTFa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboBoxArea = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        frameSeq = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jTFitersSeq = new javax.swing.JTextField();
        butSetSeq = new javax.swing.JButton();
        frameDuffing = new javax.swing.JFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTFc1_Duf = new javax.swing.JTextField();
        jTFc2_Duf = new javax.swing.JTextField();
        jTFa_Duf = new javax.swing.JTextField();
        jTFb_Duf = new javax.swing.JTextField();
        frameIFSrand = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        listIFS = new javax.swing.JList();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        drawPanel = new DrawPanel();
        panelArea = new javax.swing.JPanel();
        jLabCent = new javax.swing.JLabel();
        jTFcentX = new javax.swing.JTextField();
        jTFcentY = new javax.swing.JTextField();
        jLabDist = new javax.swing.JLabel();
        jTFdist = new javax.swing.JTextField();
        butTraec = new javax.swing.JButton();
        butMove = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuSettings = new javax.swing.JMenu();
        menuSys = new javax.swing.JMenuItem();
        menuParams = new javax.swing.JMenuItem();
        menuProps = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        frameSys.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frameSys.setTitle("Choose system");
        frameSys.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        frameSys.setResizable(false);
        frameSys.setSize(new java.awt.Dimension(250, 290));

        sampleList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        sampleList.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jScrollPane1.setViewportView(sampleList);

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Map", "ODE", "Fractal" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameSysLayout = new javax.swing.GroupLayout(frameSys.getContentPane());
        frameSys.getContentPane().setLayout(frameSysLayout);
        frameSysLayout.setHorizontalGroup(
            frameSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameSysLayout.createSequentialGroup()
                .addGroup(frameSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameSysLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameSysLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frameSysLayout.setVerticalGroup(
            frameSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameSysLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        frameRK4.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frameRK4.setTitle("RK4 Set");
        frameRK4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        frameRK4.setResizable(false);
        frameRK4.setSize(new java.awt.Dimension(150, 150));

        jLabel1.setText("Iterations");

        jLabel2.setText("Step");

        jTFiters.setText("500");
        jTFiters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFitersActionPerformed(evt);
            }
        });

        jTFstep.setText("0.01");
        jTFstep.setToolTipText("");

        buSetRK4.setText("OK");
        buSetRK4.setToolTipText("");
        buSetRK4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buSetRK4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameRK4Layout = new javax.swing.GroupLayout(frameRK4.getContentPane());
        frameRK4.getContentPane().setLayout(frameRK4Layout);
        frameRK4Layout.setHorizontalGroup(
            frameRK4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameRK4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameRK4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(frameRK4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFstep)
                    .addComponent(jTFiters, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameRK4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buSetRK4)
                .addGap(43, 43, 43))
        );
        frameRK4Layout.setVerticalGroup(
            frameRK4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameRK4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameRK4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTFiters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frameRK4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFstep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buSetRK4)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        frameChirikov.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frameChirikov.setTitle("Chirikov map");
        frameChirikov.setResizable(false);
        frameChirikov.setSize(new java.awt.Dimension(260, 200));

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextPane1.setText("X (n+1) = X (n) + P (n+1)\nP (n+1) = P (n) + a*sin (X (n))");
        jScrollPane3.setViewportView(jTextPane1);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("a");

        jTFa.setText("0.7");

        jLabel4.setText("Area");

        comboBoxArea.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        comboBoxArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "R2", "Cylindr (X mod 2PI)", "Torus ((X, P) mod 2PI)" }));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameChirikovLayout = new javax.swing.GroupLayout(frameChirikov.getContentPane());
        frameChirikov.getContentPane().setLayout(frameChirikovLayout);
        frameChirikovLayout.setHorizontalGroup(
            frameChirikovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameChirikovLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameChirikovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(frameChirikovLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frameChirikovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(comboBoxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        frameChirikovLayout.setVerticalGroup(
            frameChirikovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameChirikovLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(frameChirikovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(frameChirikovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFa)
                        .addComponent(jLabel4)
                        .addComponent(comboBoxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        frameSeq.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frameSeq.setTitle("Sequnece props");
        frameSeq.setResizable(false);
        frameSeq.setSize(new java.awt.Dimension(225, 130));

        jLabel5.setText("Num of iter-s");

        jTFitersSeq.setText("300");
        jTFitersSeq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFitersSeqActionPerformed(evt);
            }
        });

        butSetSeq.setText("OK");
        butSetSeq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSetSeqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameSeqLayout = new javax.swing.GroupLayout(frameSeq.getContentPane());
        frameSeq.getContentPane().setLayout(frameSeqLayout);
        frameSeqLayout.setHorizontalGroup(
            frameSeqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameSeqLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameSeqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(butSetSeq)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jTFitersSeq, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        frameSeqLayout.setVerticalGroup(
            frameSeqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameSeqLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(frameSeqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFitersSeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(butSetSeq)
                .addGap(17, 17, 17))
        );

        frameDuffing.setTitle("Duffing Eq");
        frameDuffing.setResizable(false);
        frameDuffing.setSize(new java.awt.Dimension(260, 250));

        jTextPane2.setEditable(false);
        jTextPane2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextPane2.setText("x' = y\ny' = -c1*x - c2*(x^3) + a*sin(b*t)");
        jScrollPane4.setViewportView(jTextPane2);

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("c1");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("c2");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("a");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("b");

        jTFc1_Duf.setText("1");

        jTFc2_Duf.setText("-1");
        jTFc2_Duf.setToolTipText("");

        jTFa_Duf.setText("0");

        jTFb_Duf.setText("1");

        javax.swing.GroupLayout frameDuffingLayout = new javax.swing.GroupLayout(frameDuffing.getContentPane());
        frameDuffing.getContentPane().setLayout(frameDuffingLayout);
        frameDuffingLayout.setHorizontalGroup(
            frameDuffingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameDuffingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameDuffingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addGroup(frameDuffingLayout.createSequentialGroup()
                        .addGroup(frameDuffingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frameDuffingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(frameDuffingLayout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTFb_Duf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(frameDuffingLayout.createSequentialGroup()
                                    .addGroup(frameDuffingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(frameDuffingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTFc2_Duf, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                        .addComponent(jTFa_Duf))))
                            .addGroup(frameDuffingLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFc1_Duf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(frameDuffingLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frameDuffingLayout.setVerticalGroup(
            frameDuffingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameDuffingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frameDuffingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTFc1_Duf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameDuffingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTFc2_Duf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameDuffingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTFa_Duf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameDuffingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTFb_Duf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        frameIFSrand.setTitle("IFS (rand. alg.)");
        frameIFSrand.setResizable(false);
        frameIFSrand.setSize(new java.awt.Dimension(260, 200));

        jScrollPane2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        listIFS.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        listIFS.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CommonIFS[] cifsArr = {CommonIFS.SierpinskiTriangle, 
            CommonIFS.SierpinskiCarpet, CommonIFS.Fern, CommonIFS.Crystal};
        listIFS.setListData(cifsArr);

        jScrollPane2.setViewportView(listIFS);

        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameIFSrandLayout = new javax.swing.GroupLayout(frameIFSrand.getContentPane());
        frameIFSrand.getContentPane().setLayout(frameIFSrandLayout);
        frameIFSrandLayout.setHorizontalGroup(
            frameIFSrandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameIFSrandLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        frameIFSrandLayout.setVerticalGroup(
            frameIFSrandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameIFSrandLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameIFSrandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SysBuilder");
        setResizable(false);

        jPanel1.setToolTipText("contentPanel");
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 515));

        drawPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        drawPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        jLabCent.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabCent.setText("Centre(x, y)");

        jTFcentX.setText("0");

        jTFcentY.setText("0");

        jLabDist.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabDist.setText("Distance");

        jTFdist.setText("2");

        butTraec.setText("Next Iteration");
        butTraec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTraecActionPerformed(evt);
            }
        });

        butMove.setText("Move");
        butMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAreaLayout = new javax.swing.GroupLayout(panelArea);
        panelArea.setLayout(panelAreaLayout);
        panelAreaLayout.setHorizontalGroup(
            panelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreaLayout.createSequentialGroup()
                .addGroup(panelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAreaLayout.createSequentialGroup()
                        .addComponent(jTFcentX, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTFcentY, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTFdist, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAreaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabCent)
                            .addComponent(jLabDist)))
                    .addGroup(panelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(butMove, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butTraec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAreaLayout.setVerticalGroup(
            panelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabCent)
                .addGap(18, 18, 18)
                .addGroup(panelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFcentX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFcentY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabDist)
                .addGap(18, 18, 18)
                .addComponent(jTFdist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butMove)
                .addGap(24, 24, 24)
                .addComponent(butTraec)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(drawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        drawPanel.getAccessibleContext().setAccessibleName("");
        panelArea.getAccessibleContext().setAccessibleName("setPanel");
        panelArea.getAccessibleContext().setAccessibleDescription("");

        menuFile.setText("File");

        jMenuItem1.setText("Save as");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuFile.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuFile.add(jMenuItem2);

        jMenuBar1.add(menuFile);

        menuSettings.setText("Settings");

        menuSys.setText("Choose system");
        menuSys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSysActionPerformed(evt);
            }
        });
        menuSettings.add(menuSys);

        menuParams.setText("Change params");
        menuParams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuParamsActionPerformed(evt);
            }
        });
        menuSettings.add(menuParams);

        menuProps.setText("Properties...");
        menuProps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPropsActionPerformed(evt);
            }
        });
        menuSettings.add(menuProps);

        jMenuBar1.add(menuSettings);

        jMenu3.setText("Help");

        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, 654, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("contentPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "This program was created by Ivanov Artyom.", "About program", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void butTraecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTraecActionPerformed
        // TODO add your handling code here:
        if (ds instanceof DiffEq2D) {
            DiffEq2D de2 = (DiffEq2D) ds;

            if (de2.isPeriodic()) {
                de2.poincareMap();
            } else {
                de2.rk4();
            }

            drawPanel.repaint();
        } else if (ds instanceof MapDS2D) {
            MapDS2D map = (MapDS2D) ds;
            map.getSequence();
            drawPanel.repaint();
        } else if (ds instanceof FractalRandIFS) {
            FractalRandIFS fr = (FractalRandIFS) ds;

            fr.applyIFS();

            drawPanel.repaint();
        }
    }//GEN-LAST:event_butTraecActionPerformed

    private void menuSysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSysActionPerformed
        // TODO add your handling code here:
        frameSys.setVisible(true);
        frameSys.getContentPane().repaint();
    }//GEN-LAST:event_menuSysActionPerformed

    private void butMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMoveActionPerformed
        // TODO add your handling code here:
        if (ds instanceof DiffEq2D) {
            DiffEq2D de2 = (DiffEq2D) ds;

            //if it fails to set new values, it uses the old ones
            double newX = de2.getTr().getxCent();
            double newY = de2.getTr().getyCent();
            double newD = de2.getTr().getDist();

            try {
                newX = Double.parseDouble(jTFcentX.getText().trim());
                newY = Double.parseDouble(jTFcentY.getText().trim());
                newD = Double.parseDouble(jTFdist.getText().trim());
            } catch (Exception e) {
                System.err.println(e);
            }

            de2.getTr().setEdges(newX, newY, newD);

            drawPanel.repaint();
        } else if (ds instanceof MapDS2D) {
            MapDS2D de2 = (MapDS2D) ds;

            //if it fails to set new values, it uses the old ones
            double newX = de2.getTr().getxCent();
            double newY = de2.getTr().getyCent();
            double newD = de2.getTr().getDist();

            try {
                newX = Double.parseDouble(jTFcentX.getText().trim());
                newY = Double.parseDouble(jTFcentY.getText().trim());
                newD = Double.parseDouble(jTFdist.getText().trim());
            } catch (Exception e) {
                System.err.println(e);
            }

            de2.getTr().setEdges(newX, newY, newD);

            drawPanel.repaint();
        }
    }//GEN-LAST:event_butMoveActionPerformed

    private void buSetRK4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buSetRK4ActionPerformed
        // TODO add your handling code here:
        if (ds instanceof DiffEq) {
            DiffEq de = (DiffEq) ds;

            int newIter = de.getIterCount();
            double newSt = de.getStep();

            try {
                newIter = Integer.parseInt(jTFiters.getText().trim());
                newSt = Double.parseDouble(jTFstep.getText().trim());
            } catch (Exception e) {
                System.err.println(e);
            }

            de.setIterCount(newIter);
            de.setStep(newSt);

            frameRK4.setVisible(false);
        }
    }//GEN-LAST:event_buSetRK4ActionPerformed

    private void menuPropsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPropsActionPerformed
        // TODO add your handling code here:
        if (ds instanceof DiffEq) {
            frameRK4.setVisible(true);
            frameRK4.getContentPane().repaint();
        } else if (ds instanceof MapDS) {
            frameSeq.setVisible(true);
            frameSeq.getContentPane().repaint();
        }
    }//GEN-LAST:event_menuPropsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        frameSys.setVisible(false);

        try {
            String choice = (String) sampleList.getSelectedValue();
            switch (choice) {
                case "Chirikov":
                    frameChirikov.setVisible(true);
                    frameChirikov.repaint();
                    break;
                case "DuffingEq":
                    frameDuffing.setVisible(true);
                    frameDuffing.repaint();
                    break;
                case "IFS (rand)":
                    frameIFSrand.setVisible(true);
                    frameIFSrand.repaint();

            }
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // default value
        double a = 0.7;

        try {
            a = Double.parseDouble(jTFa.getText().trim());
        } catch (Exception e) {
            System.err.println(e);
        }

        Area ar;
        switch (comboBoxArea.getSelectedIndex()) {
            case 0:
                ar = Area.R2;
                break;
            case 1:
                ar = Area.CYLINDER;
                break;
            case 2:
            default:
                ar = Area.TORUS;
        }

        ds = new Chirikov(a, ar);
        ((DrawPanel) drawPanel).setDs(ds);

        frameChirikov.setVisible(false);
        //set default values in the text fileds
        jTFcentX.setText("0");
        jTFcentY.setText("0");
        jTFdist.setText("2");
        jTFitersSeq.setText("300");
        drawPanel.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menuParamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuParamsActionPerformed
        // TODO add your handling code here:
        if (ds instanceof Chirikov) {
            frameChirikov.setVisible(true);
            frameChirikov.getContentPane().repaint();
        } else if (ds instanceof DuffingEq) {
            frameDuffing.setVisible(true);
            frameDuffing.getContentPane().repaint();
        } else if (ds instanceof FractalRandIFS) {
            frameIFSrand.setVisible(true);
            frameIFSrand.getContentPane().repaint();
        }
    }//GEN-LAST:event_menuParamsActionPerformed

    private void butSetSeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSetSeqActionPerformed
        // TODO add your handling code here:
        if (ds instanceof MapDS) {
            MapDS map = (MapDS) ds;

            int newIter = map.getIterCount();

            try {
                newIter = Integer.parseInt(jTFitersSeq.getText().trim());
            } catch (Exception e) {
                System.err.println(e);
            }

            map.setIterCount(newIter);

            frameSeq.setVisible(false);
        }
    }//GEN-LAST:event_butSetSeqActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        //if it fails to set new params, use default
        double c1 = 1;
        double c2 = -1;
        double a = 0;
        double b = 1;

        try {
            c1 = Double.parseDouble(jTFc1_Duf.getText().trim());
            c2 = Double.parseDouble(jTFc2_Duf.getText().trim());
            a = Double.parseDouble(jTFa_Duf.getText().trim());
            b = Double.parseDouble(jTFb_Duf.getText().trim());
        } catch (Exception e) {
            System.err.println(e);
        }

        ds = new DuffingEq(c1, c2, a, b);
        frameDuffing.setVisible(false);

        ((DrawPanel) drawPanel).setDs(ds);
        //set default values in the text fileds
        jTFcentX.setText("0");
        jTFcentY.setText("0");
        jTFdist.setText("2");
        jTFiters.setText("500");
        jTFstep.setText("0.01");

        drawPanel.repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String choice = (String) jComboBox1.getSelectedItem();
        switch (choice) {
            case "Map":
                sampleList.setListData(maps);
                break;
            case "Fractal":
                sampleList.setListData(fractals);
                break;
            case "ODE":
            default:
                sampleList.setListData(des);
        }

        //set default values
        jTFcentX.setText("0");
        jTFcentY.setText("0");
        jTFdist.setText("2");

        frameSys.getContentPane().repaint();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTFitersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFitersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFitersActionPerformed

    private void jTFitersSeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFitersSeqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFitersSeqActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CommonIFS choiceIFS = (CommonIFS) listIFS.getSelectedValue();

        ds = new FractalRandIFS(IFS.getInstance(choiceIFS));
        ((DrawPanel) drawPanel).setDs(ds);

        frameIFSrand.setVisible(false);
        drawPanel.repaint();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String format = "png";
        File saveFile = new File(ds.toString() + "." + format);
        JFileChooser chooser = new JFileChooser();
        chooser.setSelectedFile(saveFile);
        
        int rval = chooser.showSaveDialog(jMenuItem1);
        if (rval == JFileChooser.APPROVE_OPTION) {
            saveFile = chooser.getSelectedFile();

            try {
                ImageIO.write(ds.getImage(), format, saveFile);
            } catch (IOException ex) {
                System.err.println("Exception while the image was  being saved: " + ex);
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MyJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buSetRK4;
    private javax.swing.JButton butMove;
    private javax.swing.JButton butSetSeq;
    private javax.swing.JButton butTraec;
    private javax.swing.JComboBox comboBoxArea;
    private javax.swing.JPanel drawPanel;
    private javax.swing.JFrame frameChirikov;
    private javax.swing.JFrame frameDuffing;
    private javax.swing.JFrame frameIFSrand;
    private javax.swing.JFrame frameRK4;
    private javax.swing.JFrame frameSeq;
    private javax.swing.JFrame frameSys;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabCent;
    private javax.swing.JLabel jLabDist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTFa;
    private javax.swing.JTextField jTFa_Duf;
    private javax.swing.JTextField jTFb_Duf;
    private javax.swing.JTextField jTFc1_Duf;
    private javax.swing.JTextField jTFc2_Duf;
    private javax.swing.JTextField jTFcentX;
    private javax.swing.JTextField jTFcentY;
    private javax.swing.JTextField jTFdist;
    private javax.swing.JTextField jTFiters;
    private javax.swing.JTextField jTFitersSeq;
    private javax.swing.JTextField jTFstep;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JList listIFS;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuParams;
    private javax.swing.JMenuItem menuProps;
    private javax.swing.JMenu menuSettings;
    private javax.swing.JMenuItem menuSys;
    private javax.swing.JPanel panelArea;
    private javax.swing.JList sampleList;
    // End of variables declaration//GEN-END:variables
}
